"""UI カラー・フォント定義"""

from constants import (
    MINHAYA_PURPLE, MINHAYA_PURPLE_DARK, MINHAYA_PURPLE_LIGHT,
    MINHAYA_GOLD, MINHAYA_BG, MINHAYA_BG_CARD,
    MINHAYA_TEXT, MINHAYA_TEXT_DIM,
    MINHAYA_GREEN, MINHAYA_RED, MINHAYA_ORANGE,
    CAPTURE_BORDER_COLOR, CAPTURE_BORDER_ACTIVE,
    FONT_FAMILY,
)

# --- フォント設定 ---
FONT_QUESTION = (FONT_FAMILY, 16)
FONT_ANSWER = (FONT_FAMILY, 32, "bold")
FONT_ANSWER_READING = (FONT_FAMILY, 14)
FONT_STATUS = (FONT_FAMILY, 11)
FONT_LABEL = (FONT_FAMILY, 12)
FONT_BUTTON = (FONT_FAMILY, 13)
FONT_SMALL = (FONT_FAMILY, 10)

# re-export for convenience
__all__ = [
    "MINHAYA_PURPLE", "MINHAYA_PURPLE_DARK", "MINHAYA_PURPLE_LIGHT",
    "MINHAYA_GOLD", "MINHAYA_BG", "MINHAYA_BG_CARD",
    "MINHAYA_TEXT", "MINHAYA_TEXT_DIM",
    "MINHAYA_GREEN", "MINHAYA_RED", "MINHAYA_ORANGE",
    "CAPTURE_BORDER_COLOR", "CAPTURE_BORDER_ACTIVE",
    "FONT_FAMILY",
    "FONT_QUESTION", "FONT_ANSWER", "FONT_ANSWER_READING",
    "FONT_STATUS", "FONT_LABEL", "FONT_BUTTON", "FONT_SMALL",
]
